# Just TRUE or False result

In [7]:
import face_recognition

In [8]:
image = face_recognition.load_image_file("nabin.jpg")
face_locations = face_recognition.face_locations(image)

In [10]:
face_landmarks_list = face_recognition.face_landmarks(image)

In [12]:
unknown_image = face_recognition.load_image_file("jtur.jpg")

In [13]:
nabin_encoding = face_recognition.face_encodings(image)[0]
unknown_image = face_recognition.face_encodings(unknown_image)[0]

In [14]:
results = face_recognition.compare_faces([nabin_encoding], unknown_image)

In [15]:
results

[True]

# explore

In [16]:
image

array([[[ 4,  5,  7],
        [ 3,  4,  6],
        [ 2,  3,  5],
        ...,
        [13, 14, 16],
        [13, 14, 16],
        [13, 14, 16]],

       [[ 3,  4,  6],
        [ 2,  3,  5],
        [ 1,  2,  4],
        ...,
        [12, 13, 15],
        [12, 13, 15],
        [12, 13, 15]],

       [[ 2,  3,  5],
        [ 1,  2,  4],
        [ 1,  2,  4],
        ...,
        [11, 12, 14],
        [11, 12, 14],
        [11, 12, 14]],

       ...,

       [[ 1,  1,  3],
        [ 1,  1,  3],
        [ 1,  1,  3],
        ...,
        [ 9,  9, 11],
        [ 9,  9, 11],
        [ 9,  9, 11]],

       [[ 1,  1,  3],
        [ 1,  1,  3],
        [ 1,  1,  3],
        ...,
        [ 8,  8, 10],
        [ 8,  8, 10],
        [ 8,  8, 10]],

       [[ 1,  1,  3],
        [ 1,  1,  3],
        [ 1,  1,  3],
        ...,
        [ 8,  8, 10],
        [ 7,  7,  9],
        [ 7,  7,  9]]], dtype=uint8)

In [17]:
face_locations

[(322, 717, 477, 562)]

In [18]:
face_landmarks_list

[{'chin': [(559, 371),
   (561, 391),
   (564, 411),
   (569, 432),
   (577, 452),
   (590, 469),
   (606, 485),
   (624, 497),
   (647, 500),
   (669, 495),
   (683, 481),
   (694, 465),
   (703, 446),
   (707, 427),
   (710, 406),
   (711, 386),
   (710, 365)],
  'left_eyebrow': [(573, 353), (581, 340), (597, 335), (613, 337), (628, 341)],
  'right_eyebrow': [(650, 341),
   (665, 335),
   (680, 332),
   (695, 337),
   (703, 350)],
  'nose_bridge': [(640, 359), (641, 372), (643, 385), (644, 398)],
  'nose_tip': [(624, 409), (634, 411), (644, 413), (653, 410), (662, 408)],
  'left_eye': [(590, 366),
   (598, 359),
   (610, 359),
   (620, 366),
   (610, 369),
   (598, 370)],
  'right_eye': [(657, 365),
   (667, 357),
   (678, 356),
   (686, 362),
   (679, 366),
   (668, 367)],
  'top_lip': [(607, 437),
   (619, 429),
   (634, 425),
   (644, 427),
   (655, 425),
   (668, 427),
   (679, 434),
   (674, 436),
   (655, 433),
   (645, 435),
   (634, 434),
   (612, 438)],
  'bottom_lip': [(679

In [19]:
unknown_image

array([-0.15306656,  0.06610941,  0.06065572, -0.02113836,  0.01318729,
       -0.0325494 , -0.0629167 , -0.08272704,  0.11245458,  0.01671924,
        0.25857973, -0.05051659, -0.16158244, -0.1414585 ,  0.03797357,
        0.06971508, -0.14443994, -0.14387546, -0.02550403, -0.06373416,
       -0.0184054 ,  0.02038954,  0.03255763,  0.12142657, -0.14990722,
       -0.37587202, -0.08197754, -0.19599372,  0.08782681, -0.1402369 ,
       -0.08460499, -0.01241699, -0.27316627, -0.0688961 ,  0.00196187,
        0.10256482,  0.05601896, -0.00834253,  0.14339301,  0.05905369,
       -0.07239519,  0.02597198,  0.01686641,  0.27975228,  0.14567271,
        0.037603  ,  0.07729158,  0.01329284,  0.0641625 , -0.24143383,
        0.11496679,  0.1292468 ,  0.12756006,  0.03141345,  0.01832539,
       -0.11570874, -0.07366179,  0.05474674, -0.1445898 ,  0.19419779,
        0.06428133,  0.06075598, -0.08789705,  0.02994604,  0.24923135,
        0.11954929, -0.12051145, -0.13687806,  0.06456979, -0.14

In [20]:
face_landmarks_list

[{'chin': [(559, 371),
   (561, 391),
   (564, 411),
   (569, 432),
   (577, 452),
   (590, 469),
   (606, 485),
   (624, 497),
   (647, 500),
   (669, 495),
   (683, 481),
   (694, 465),
   (703, 446),
   (707, 427),
   (710, 406),
   (711, 386),
   (710, 365)],
  'left_eyebrow': [(573, 353), (581, 340), (597, 335), (613, 337), (628, 341)],
  'right_eyebrow': [(650, 341),
   (665, 335),
   (680, 332),
   (695, 337),
   (703, 350)],
  'nose_bridge': [(640, 359), (641, 372), (643, 385), (644, 398)],
  'nose_tip': [(624, 409), (634, 411), (644, 413), (653, 410), (662, 408)],
  'left_eye': [(590, 366),
   (598, 359),
   (610, 359),
   (620, 366),
   (610, 369),
   (598, 370)],
  'right_eye': [(657, 365),
   (667, 357),
   (678, 356),
   (686, 362),
   (679, 366),
   (668, 367)],
  'top_lip': [(607, 437),
   (619, 429),
   (634, 425),
   (644, 427),
   (655, 425),
   (668, 427),
   (679, 434),
   (674, 436),
   (655, 433),
   (645, 435),
   (634, 434),
   (612, 438)],
  'bottom_lip': [(679

In [21]:
unknown_image

array([-0.15306656,  0.06610941,  0.06065572, -0.02113836,  0.01318729,
       -0.0325494 , -0.0629167 , -0.08272704,  0.11245458,  0.01671924,
        0.25857973, -0.05051659, -0.16158244, -0.1414585 ,  0.03797357,
        0.06971508, -0.14443994, -0.14387546, -0.02550403, -0.06373416,
       -0.0184054 ,  0.02038954,  0.03255763,  0.12142657, -0.14990722,
       -0.37587202, -0.08197754, -0.19599372,  0.08782681, -0.1402369 ,
       -0.08460499, -0.01241699, -0.27316627, -0.0688961 ,  0.00196187,
        0.10256482,  0.05601896, -0.00834253,  0.14339301,  0.05905369,
       -0.07239519,  0.02597198,  0.01686641,  0.27975228,  0.14567271,
        0.037603  ,  0.07729158,  0.01329284,  0.0641625 , -0.24143383,
        0.11496679,  0.1292468 ,  0.12756006,  0.03141345,  0.01832539,
       -0.11570874, -0.07366179,  0.05474674, -0.1445898 ,  0.19419779,
        0.06428133,  0.06075598, -0.08789705,  0.02994604,  0.24923135,
        0.11954929, -0.12051145, -0.13687806,  0.06456979, -0.14

In [22]:
nabin_encoding

array([-0.15101288,  0.14248256,  0.09974257, -0.01591533, -0.00271878,
        0.02724418, -0.07126129, -0.09104238,  0.17076053, -0.00601981,
        0.20442906, -0.01487628, -0.21316817, -0.12164856,  0.02857115,
        0.08244398, -0.1321917 , -0.12778874, -0.06512444, -0.08091196,
       -0.03634795,  0.03130123,  0.0800406 ,  0.06552889, -0.18071997,
       -0.35426834, -0.09439939, -0.18926096,  0.07178107, -0.10943642,
       -0.11128259, -0.06850202, -0.26124588, -0.02927863, -0.05447419,
        0.0410634 ,  0.05952906, -0.01072455,  0.11992675,  0.03842495,
       -0.13096334, -0.01609164, -0.00256129,  0.23207344,  0.17246301,
        0.05193587,  0.03918387,  0.0165997 ,  0.0622796 , -0.21340665,
        0.14173795,  0.13275324,  0.07570837,  0.05385421,  0.05134707,
       -0.12981208, -0.09810571,  0.05525039, -0.12282954,  0.13281   ,
        0.05017255,  0.05252573, -0.06596204, -0.01098661,  0.27346107,
        0.17638165, -0.12126219, -0.14725471,  0.06311211, -0.15

In [23]:
unknown_image

array([-0.15306656,  0.06610941,  0.06065572, -0.02113836,  0.01318729,
       -0.0325494 , -0.0629167 , -0.08272704,  0.11245458,  0.01671924,
        0.25857973, -0.05051659, -0.16158244, -0.1414585 ,  0.03797357,
        0.06971508, -0.14443994, -0.14387546, -0.02550403, -0.06373416,
       -0.0184054 ,  0.02038954,  0.03255763,  0.12142657, -0.14990722,
       -0.37587202, -0.08197754, -0.19599372,  0.08782681, -0.1402369 ,
       -0.08460499, -0.01241699, -0.27316627, -0.0688961 ,  0.00196187,
        0.10256482,  0.05601896, -0.00834253,  0.14339301,  0.05905369,
       -0.07239519,  0.02597198,  0.01686641,  0.27975228,  0.14567271,
        0.037603  ,  0.07729158,  0.01329284,  0.0641625 , -0.24143383,
        0.11496679,  0.1292468 ,  0.12756006,  0.03141345,  0.01832539,
       -0.11570874, -0.07366179,  0.05474674, -0.1445898 ,  0.19419779,
        0.06428133,  0.06075598, -0.08789705,  0.02994604,  0.24923135,
        0.11954929, -0.12051145, -0.13687806,  0.06456979, -0.14

In [24]:
results

[True]

In [25]:
face_locations

[(322, 717, 477, 562)]

# Why numpy is sooo seen everywhere?

# Now let's use camera